name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: â˜• Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: âœ… Build e Testes
        run: |
          echo "ğŸ” Rodando build Maven"
          cd app
          mvn clean package

      - name: ğŸ³ Build da imagem Docker
        run: |
          echo "ğŸ³ Criando imagem Docker"
          docker build -t ${{ secrets.DOCKER_USER }}/project-01-ci-cd:latest .

      - name: ğŸ” Scan de seguranÃ§a com Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/project-01-ci-cd:latest
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: ğŸ”‘ Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ“¤ Push da imagem
        run: |
          echo "ğŸš€ Publicando imagem no Docker Hub"
          docker push ${{ secrets.DOCKER_USER }}/project-01-ci-cd:latest

